name: branch test

on:
  push:
    branches-ignore: [gh-pages, main]
  workflow_dispatch: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: set up
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - name: check out
      uses: actions/checkout@v2
    - name: cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner-os }}-go-
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd cmd/gonin-node
        go build

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: go test -v -cover -coverprofile=cover.out ./...
    - name: coverage
      run: go tool cover -func cover.out

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: go-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
