name: main

on:
  push:
    branches: [main, update20210828]
  workflow_dispatch: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: set up
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go
    - name: check out
      uses: actions/checkout@v2
    - name: cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - name: Download Modules
      if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd cmd/gonin-node
        go build

  doc:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install godoc-static
      run: |
        cd /tmp
        go get golang.org/x/tools/cmd/godoc@latest
        go get gitlab.com/tslocum/godoc-static@latest
    - name: mkdir
      run: mkdir -p output
    - name: generate doc
      run: |
        $GOPATH/bin/godoc-static -zip '' -destination=output -site-description-file=desc.md -site-name=gonin-node github.com/wtnb75/gonin-node

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: go test -v -cover -coverprofile=cover.out ./...
    - name: mkdir
      run: |
        mkdir -p output/cover
    - name: coverage
      run: go tool cover -html cover.out -o output/cover/index.html

  deploy:
    needs: [test, doc]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        force_orphan: true

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: go-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
