name: main

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: set up
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - name: check out
      uses: actions/checkout@v2
    - name: cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - name: Download Modules
      if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd cmd/gonin-node
        go build

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: go test -v -cover -coverprofile=cover.out ./...
    - name: mkdir
      run: |
        mkdir output
        touch output/.nojekyll
    - name: coverage
      run: go tool cover -html cover.out -o output/index.html
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        force_orphan: true

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: go-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
